Add go-fmt to CI. (#300)
* Add go-fmt to CI.

* Fix failing gofmt error.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,6 +7,23 @@ on:
       - main
 
 jobs:
+  go-fmt:
+    name: go-fmt
+    runs-on: ubuntu-20.04
+
+    steps:
+      - name: Install Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: "1.16"
+
+      - name: Checkout branch
+        uses: actions/checkout@v3
+
+      # Fail if go-fmt recommends any changes.
+      - name: Run go fmt
+        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
+
   go-test-postgres:
     name: go-test-postgres
     runs-on: ubuntu-20.04
@@ -41,6 +58,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Cache dependencies
+        id: cache-dependencies
         uses: actions/cache@v2
         with:
           path: |
@@ -50,7 +68,9 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-go-
 
+      # Install dependencies if not found in cache.
       - name: Install dependencies
+        if: steps.cache-dependencies.outputs.cache-hit != 'true'
         run: go mod download && go install
 
       - name: Build package
